version: "3"
services:
#Mysql db
  mysql-container:
    build: ./mysql-server/
    ports: 
     - 3306:3306
  #NodeJs service
  webserver:
    build: ./web-app/
    ports: 
      - 3000:3000
    depends_on: 
      - mysql-container
  
